### ISSUE TITLE
Usage example

### ISSUE THREAD

**Issue by lropero** [luzzif/binance-api-client#19]
How is this supposed to be used?

I was able to make this work by doing this in my Express project (a REST API wrapping this library):
```
var binance = require('binance-api-client');
new binance.BinanceApiClient(binanceKey, binanceSecret);
```

But is this ok? I've read that calling **new** without assignment is an anti-pattern since this probably means that the function called has side effects (e.g. setting globals, more on this [here](https://stackoverflow.com/questions/2594415/is-it-bad-practice-to-not-assign-a-new-object-to-a-variable)).

Thanks for this incredible well-done library.

Cheers.-

**Comment by luzzif** [comment]
First of all, thanks for the kind words.

Secondly, and coming to the actual question, calling ```new``` every time the library has to be used is rather redundant (and yes, it's actually pointless and wasteful on resources, mainly memory, if you don't store the instance anywhere in your code). The way I manage it in TypeScript is by keeping only one instance at a time always ready-for-use leveraging a singleton pattern, where the singleton itself acts as a resources manager.

Honestly, I wouldn't be able to help you regarding the equivalent implementation in vanilla JS/ES since I'm actually not too fond of it, to put it mildly, but try to Google it using the hints I tried to give you and I'm sure you will pull it off.

Thanks again for the kind words mate, I appreciate it very much!
