### ISSUE TITLE
Type 'undefined' cannot be used as an index type.

### ISSUE THREAD

**Issue by gemmell** [luzzif/binance-api-client#5]
My setup is warning me about something in `public async placeOrder` 

`[ "newOrderRespType", ResponseType[ responseType] ]` - `Type 'undefined' cannot be used as an index type.`

I'm assuming it defaults to `ACKNOWLEDGEMENT` because `undefined` is falsey is 0 (yay js), however it might be good to be explicit about it. 

Loving the library though.

**Comment by luzzif** [comment]
You are right, my bad I forgot to handle the situation properly. In the latest version (2.1.2) I'm actually handling it, so that if you specify ```responseType``` as ```null``` or ```undefined```, the parameter won't be sent to Binance, giving you a ```RESULT``` response type, as per [documentation](https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#new-order--trade). Thanks for the kind words anyway!
